# Matugen Hyprland Colors

$background = rgb(0f1417)

$error = rgb(ffb4ab)

$error_container = rgb(93000a)

$inverse_on_surface = rgb(2c3134)

$inverse_primary = rgb(0b6780)

$inverse_surface = rgb(dee3e6)

$on_background = rgb(dee3e6)

$on_error = rgb(690005)

$on_error_container = rgb(ffdad6)

$on_primary = rgb(003544)

$on_primary_container = rgb(baeaff)

$on_primary_fixed = rgb(001f29)

$on_primary_fixed_variant = rgb(004d62)

$on_secondary = rgb(1e333c)

$on_secondary_container = rgb(cfe6f1)

$on_secondary_fixed = rgb(071e26)

$on_secondary_fixed_variant = rgb(354a53)

$on_surface = rgb(dee3e6)

$on_surface_variant = rgb(c0c8cc)

$on_tertiary = rgb(2d2d4d)

$on_tertiary_container = rgb(e1dfff)

$on_tertiary_fixed = rgb(181837)

$on_tertiary_fixed_variant = rgb(434465)

$outline = rgb(8a9296)

$outline_variant = rgb(40484c)

$primary = rgb(89d0ed)

$primary_container = rgb(004d62)

$primary_fixed = rgb(baeaff)

$primary_fixed_dim = rgb(89d0ed)

$scrim = rgb(000000)

$secondary = rgb(b3cad5)

$secondary_container = rgb(354a53)

$secondary_fixed = rgb(cfe6f1)

$secondary_fixed_dim = rgb(b3cad5)

$shadow = rgb(000000)

$source_color = rgb(3b5864)

$surface = rgb(0f1417)

$surface_bright = rgb(353a3d)

$surface_container = rgb(1b2023)

$surface_container_high = rgb(252b2d)

$surface_container_highest = rgb(303638)

$surface_container_low = rgb(171c1f)

$surface_container_lowest = rgb(0a0f11)

$surface_dim = rgb(0f1417)

$surface_tint = rgb(89d0ed)

$surface_variant = rgb(40484c)

$tertiary = rgb(c4c3eb)

$tertiary_container = rgb(434465)

$tertiary_fixed = rgb(e1dfff)

$tertiary_fixed_dim = rgb(c4c3eb)

