# Default terminal alacritty
set-option -ga terminal-overrides ",*:Tc"
set -g default-terminal "alacritty"

unbind &
bind & kill-window     # No confirmation
	# Change prefix to C-a for easier typing
	unbind C-b
	set-option -g prefix C-a
	bind C-a send-prefix

# Kill pane instantly with Prefix + x
unbind x
bind x kill-pane       # No confirmation

# Unbind default pane movement key (optional if you want to keep it)
#unbind h

# Split window horizontally (side-by-side panes) with Prefix + v
bind v split-window -h

# Split window vertically (stacked panes) with Prefix + h
bind H split-window -v


#hjkl pane movement
# Vi-style pane movement (Prefix + h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload tmux configuration with Prefix + r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Enable mouse scrolling
set -g mouse on
# --- Atom OneDark Tmux Theme ---
# Plugin manager (TPM) required
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'odedlaz/tmux-onedark-theme'

set -g @onedark_time_format "%I:%M %p"
setenv -g SHOW_DIRECTORY_NAME 1


# set -g @plugin 'heuristicAL/tmux-atom-onedark'
# Set theme flavour (only 'dark' available)
# set -g @onedark_flavour 'dark'
# # Optional: Enable window tabs
# set -g @onedark_window_tabs_enabled on
# # Optional: Set separators
# set -g @onedark_left_separator "█"
# set -g @onedark_right_separator "█"
# # Optional: Enable date/time, user, host
# set -g @onedark_date_time "%Y-%m-%d %H:%M"
# set -g @onedark_user "on"
# set -g @onedark_host "on"
# # Optional: Custom left status
# set -g @onedark_left_status "#{battery_status_bg} Batt: #{battery_icon} #{battery_percentage} #{battery_remain}"
# # Optional: Status justify
# set -g @onedark_status_justify "centre"
# --- End Atom OneDark Tmux Theme ---

run '~/.tmux/plugins/tpm/tpm'
