
# █▄░█ █░█ █ █▀▄ █ ▄▀█
# █░▀█ ▀▄▀ █ █▄▀ █ █▀█

# See https://wiki.hyprland.org/Nvidia/

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,1
env = XCURSOR_SIZE,26
env = XCURSOR_THEME,Emo
env = WLR_NO_HARDWARE_CURSORS,1

# Fix for orphan/stuck cursor on NVIDIA (modern Hyprland)
cursor {
    no_hardware_cursors = true
    enable_hyprcursor = false
    hide_on_key_press = false
}
