# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hypr.land/Configuring/Window-Rules/

# 

windowrule = fullscreen on, match:class ^(steam_app_2357570)$
windowrule = fullscreen on, match:class ^(Overwatch)$

windowrule = float on, match:class ^(vlc)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Library)$
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = float on, match:class ^(qt5ct)$
windowrule = float on, match:class ^(qt6ct)$
windowrule = float on, match:class ^(org.kde.ark)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(yad)$
windowrule = float on, center on, match:class ^(gnome-calculator)$
windowrule = float on, center on, match:class ^(org.gnome.Loupe)$

windowrule = size 360 500, match:class ^(gnome-calculator)$
windowrule = size 1200 800, match:class ^(org.gnome.Loupe)$
windowrule = size 920 450, match:class ^(org.pulseaudio.pavucontrol)$

windowrule = no_blur on, match:class ^()$, match:title ^()$
 



